apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: teekeet.com
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: himeshramjee/auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: himeshramjee/teekeet-service
      context: teekeet-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: himeshramjee/teekeet-client-web-app
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "pages/**/*.js"
            dest: .
