apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: chaiwala/auth-service
          resources:
            requests:
              memory: "512Mi"
              cpu: "1m"
            limits:
              memory: "2048Mi"
              cpu: "250m"
          ports:
            - containerPort: 7000
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: teekeet-jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: auth-service
      protocol: TCP
      port: 7000
      targetPort: 7000
