apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-depl
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: himeshramjee/order-service
          resources:
            requests:
              memory: "100Mi"
              cpu: "1m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 7002
          env:
            - name: PORT
              value: "7002"
            - name: MONGO_URI
              value: "mongodb://order-service-mongo-db-clusterip-srv:27017/orders"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: teekeet-jwt-secret
                  key: JWT_KEY
            - name: MAX_SIZE_JSON_REQUEST
              value: "10KB"
            - name: NATS_URI
              value: "nats://nats-streaming-server-clusterip-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "teekeet-streaming-cluster"
            - name: NATS_CLIENT_ID_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ORDER_EXPIRATION_WINDOW_SECONDS
              value: "900"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: order-service
      protocol: TCP
      port: 7002
      targetPort: 7002
