apiVersion: apps/v1
kind: Deployment
metadata:
  name: teekeet-service-depl
spec:
  selector:
    matchLabels:
      app: teekeet-service
  template:
    metadata:
      labels:
        app: teekeet-service
    spec:
      containers:
        - name: teekeet-service
          image: himeshramjee/teekeet-service
          resources:
            requests:
              memory: "100Mi"
              cpu: "1m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 7001
          env:
            - name: MONGO_URI
              value: "mongodb://teekeet-service-mongo-db-clusterip-srv:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: teekeet-jwt-secret
                  key: JWT_KEY
            - name: MAX_SIZE_JSON_REQUEST
              value: "10KB"
            - name: NATS_URI
              value: "nats://nats-streaming-server-clusterip-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "teekeet-streaming-cluster"
            - name: NATS_CLIENT_ID_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_HEALTH_EVENTS_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: teekeet-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: teekeet-service
  ports:
    - name: teekeet-service
      protocol: TCP
      port: 7001
      targetPort: 7001
